Updated folder structure

diff --git a/.github/workflows/static_code_analysis.yml b/.github/workflows/static_code_analysis.yml
--- a/.github/workflows/static_code_analysis.yml
+++ b/.github/workflows/static_code_analysis.yml
@@ -21,10 +21,10 @@ jobs:
       run: |
         echo "Stage 1/2: Static code analysis Src folder"
         home_dir=$(pwd)
-        sub_dirs=("db"  "iot_gateway"  "logging")
+        sub_dirs=("db"  "iot_gateway"  "logging" "host_health")
         for sub_dir in ${sub_dirs[*]}; do
           echo "Linting for src/$sub_dir"
-          cd "$home_dir/src/$sub_dir" || { echo "cd error, check location"; exit 1; }
+          cd "$home_dir/home_automation_framework/$sub_dir" || { echo "cd error, check location"; exit 1; }
           pylint -j 2 --rcfile="$home_dir/.github/workflows/setup.cfg" --output-format=colorized `ls -R | grep .py$ | xargs`
         done
 
